import { useState } from "react";
import { Container, Row, Col, Tab, Tabs, Image, Button } from "react-bootstrap";



const Info = () => {
  const [key, setKey] = useState("first");

  return (
    <section id="info" className="mt-2 pb-4 h-100 mb-5">
      <Container className=" mt-4 h-100">
        <h1 className="font-weight-bold p-2 about-title mb-4 text-center titles">
          How it Works
        </h1>

        <Row className="text-dark">

        <Tabs
          id="uncontrolled-tab-example"
          defaultActiveKey="first"
        >
          <Tab id="tabTitles" eventKey="first" title="Step 1" tabClassName="text-dark" >
            <Row className="h-100 align-self-center ">
              <Col md={6} className="">
                <p className="font-weight-bold pt-3 mt-3">
                  Buy account tokens to vote on the "attentionworthiness" of
                  that account, and sell to revoke your vote. The first 1,000
                  tokens for each listing cost $0.10 each. Token price
                  automatically increases by $0.01 for each 100 tokens bought
                  afterward, managed by a bonding curve algorithm. You can list
                  anyone's account (even @elonmusk), as long as it's not already
                  listed. If you add an account owned by someone else, interest
                  will accrue to their wallet after a purchase, and they can
                  claim it anytime
                </p>
                <Button id="header-btn" variant="primary"  href="https://ideamarket.io/">Buy tokens</Button>{' '}
              </Col>
              <Col md={6}>
                <Image
                  className=" text-center"
                  src="/info1.png"
                  width="100%"
                  height="100%"
                />
              </Col>
            </Row>
          </Tab>
          <Tab eventKey="second" title="Step 2" tabClassName="text-dark">
            <Row>
              <Col md={6}>
                <p className="font-weight-bold pt-5 mt-5">
                  Money spent on tokens is held in compound.finance, a
                  decentralized lending protocol. Compound lends these deposits
                  to borrowers, who pay interest (usually 1-10% annually)
                </p>
                <Button id="header-btn" variant="primary"  href="https://ideamarket.io/">Buy tokens</Button>{' '}
              </Col>
              <Col md={6}>
                <Image
                  className="p-2"
                  src="/info2.png"
                  width="100%"
                  height="100%"
                />
              </Col>
            </Row>
          </Tab>
          <Tab eventKey="third" title="Step 3" tabClassName="text-dark">
            <Row className="">
              <Col md={6} >
                <p className="font-weight-bold pt-5 mt-5">
                  All interest generated by token deposits is paid to the owner
                  of the associated social media account.
                </p>
                <Button id="header-btn" variant="primary"  href="https://ideamarket.io/">Buy tokens</Button>{' '}
              </Col>
              <Col md={6}>
                <Image
                  className="p-2"
                  src="/info3.png"
                  width="100%"
                  height="100%"
                />
              </Col>
            </Row>
          </Tab>
        </Tabs>
        </Row>
      </Container>
    </section>
  );
};

export default Info;
